services:
  - type: web
    name: nave-agente-api
    runtime: python
    rootDir: fast_api_app
    buildCommand: pip install -r ../requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: false
      - key: DATABASE_URL
        sync: false          # você preenche no painel do Render
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        value: false
      - key: EXPIRED_TIME_TOKEN
        value: false