"""update

Revision ID: 36dfe0074a4e
Revises: c14abc417c5f
Create Date: 2026-06-17 16:05:38.113192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '36dfe0074a4e'
down_revision: Union[str, None] = 'c14abc417c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('id_visitante', sa.String(length=36), nullable=True))
    op.alter_column('messages', 'id_usuario',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'id_usuario',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('messages', 'id_visitante')
    # ### end Alembic commands ###
