"""azure db

Revision ID: 5aee76d1c61f
Revises: 422a592d83bf
Create Date: 2026-06-21 17:05:03.882913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5aee76d1c61f'
down_revision: Union[str, None] = '422a592d83bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """ op.drop_index(op.f('idx_rag_doc_type'), table_name='rag_document')
    op.drop_table('rag_document')
    op.drop_table('agente_conhecimento')
    op.drop_index(op.f('codigo_autenticidade'), table_name='sap_certificado')
    op.drop_table('sap_certificado')
    op.drop_index(op.f('idx_rag_chunk_doc'), table_name='rag_chunk')
    op.drop_table('rag_chunk')
    op.drop_index(op.f('id_pessoa'), table_name='sap_usuario')
    op.drop_index(op.f('login'), table_name='sap_usuario')
    op.drop_table('sap_usuario')
    op.drop_table('sap_bairro')
    op.drop_table('unidade_recurso_item')
    op.drop_table('sap_equipamento')
    op.drop_index(op.f('nome'), table_name='equipamento_smct')
    op.drop_table('equipamento_smct')
    op.drop_index(op.f('cpf'), table_name='sap_pessoa')
    op.drop_table('sap_pessoa')
    op.drop_table('unidade_recurso')
    op.drop_table('sap_deficiencia')
    op.drop_index(op.f('nome'), table_name='sap_grupo')
    op.drop_table('sap_grupo')
    op.drop_index(op.f('codigo'), table_name='sap_programacao')
    op.drop_table('sap_programacao')
    op.drop_index(op.f('codigo'), table_name='sap_unidade')
    op.drop_table('sap_unidade')
    op.drop_index(op.f('codigo'), table_name='sap_categoria_evento')
    op.drop_table('sap_categoria_evento')
    op.drop_index(op.f('sigla'), table_name='sap_uf')
    op.drop_table('sap_uf')
    op.drop_table('sap_cidade')
    op.drop_table('sap_espaco')
    op.drop_table('rag_embedding')
    op.drop_table('sap_tipo_espaco')
    op.drop_table('sap_evento')
    op.drop_table('sap_certificado_modelo')
    op.drop_table('sap_escolaridade')
    op.drop_table('sap_instituicao_ensino')
    op.drop_index(op.f('nome'), table_name='agente_fonte_dados')
    op.drop_table('agente_fonte_dados')
    op.drop_index(op.f('id_usuario'), table_name='sap_frequentador')
    op.drop_table('sap_frequentador')
    op.drop_table('sap_inscricao_evento') """
    op.drop_table('sap_messages')
    op.add_column('usuarios', sa.Column('criado_em', sa.DateTime(), nullable=True))
    op.drop_column('usuarios', 'admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('usuarios', 'criado_em')
    op.create_table('sap_inscricao_evento',
    sa.Column('id_inscricao_evento', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_frequentador', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_programacao', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_inscricao', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('posicao', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_cancelamento', mysql.DATETIME(), nullable=True),
    sa.Column('pre_requisitos', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_frequentador'], ['sap_frequentador.id_frequentador'], name=op.f('fk_inscricao_frequentador'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_programacao'], ['sap_programacao.id_programacao'], name=op.f('fk_inscricao_programacao'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_inscricao_evento'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sap_frequentador',
    sa.Column('id_frequentador', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('habilitado', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('data_cadastro', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['sap_usuario.id_usuario'], name=op.f('fk_frequentador_usuario'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_frequentador'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('id_usuario'), 'sap_frequentador', ['id_usuario'], unique=True)
    op.create_table('agente_fonte_dados',
    sa.Column('id_agente_fonte_dados', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('url_origem', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('tipo_fonte', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('frequencia_atualizacao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('criado_em', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('atualizado_em', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id_agente_fonte_dados'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('nome'), 'agente_fonte_dados', ['nome'], unique=True)
    op.create_table('sap_instituicao_ensino',
    sa.Column('id_instituicao_ensino', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_bairro', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sigla', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=25), nullable=True),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('categoria', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aprovada', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('removido', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_bairro'], ['sap_bairro.id_bairro'], name=op.f('fk_instituicao_bairro'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_instituicao_ensino'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sap_escolaridade',
    sa.Column('id_escolaridade', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome_escolaridade', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_escolaridade'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sap_certificado_modelo',
    sa.Column('id_certificado_modelo', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('tipo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), server_default=sa.text("'CONCLUSAO'"), nullable=False),
    sa.Column('orientacao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), server_default=sa.text("'PAISAGEM'"), nullable=True),
    sa.Column('modelo_html', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('habilitado', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('inserido_em', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('atualizado_em', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id_certificado_modelo'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sap_evento',
    sa.Column('id_evento', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('descricao', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('removido', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('habilitado', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('destacado', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('formulario_extra', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('formulario_extra_conteudo', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('data_modificacao', mysql.DATETIME(), nullable=True),
    sa.Column('id_categoria_evento', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_evento_pai', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('codigo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=5), nullable=True),
    sa.Column('codigo_sequencial', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('carga_horaria', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('imagem', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=60), nullable=True),
    sa.Column('ead', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('simpleead', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('id_organizacao_social', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_categoria_evento'], ['sap_categoria_evento.id_categoria_evento'], name=op.f('fk_evento_categoria'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_evento'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sap_tipo_espaco',
    sa.Column('id_tipo_espaco', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_espaco'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rag_embedding',
    sa.Column('embedding_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('chunk_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('embedding_vector', mysql.JSON(), nullable=False),
    sa.Column('embedding_model', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), server_default=sa.text("'text-embedding-3-small'"), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['rag_chunk.chunk_id'], name=op.f('fk_embedding_chunk'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('embedding_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sap_espaco',
    sa.Column('id_espaco', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_unidade', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_tipo_espaco', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('descricao', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('limite_tempo', mysql.TIME(), nullable=True),
    sa.Column('alerta_termino', mysql.TIME(), nullable=True),
    sa.Column('solicitavel', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('removido', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_tipo_espaco'], ['sap_tipo_espaco.id_tipo_espaco'], name=op.f('fk_espaco_tipo'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_unidade'], ['sap_unidade.id_unidade'], name=op.f('fk_espaco_unidade'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_espaco'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sap_messages',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_visitante', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('conversa', mysql.JSON(), nullable=False),
    sa.Column('criado_em', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['sap_usuario.id_usuario'], name=op.f('sap_messages_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sap_cidade',
    sa.Column('id_cidade', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_uf', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_uf'], ['sap_uf.id_uf'], name=op.f('fk_cidade_uf'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_cidade'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sap_uf',
    sa.Column('id_uf', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sigla', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2), nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_uf'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('sigla'), 'sap_uf', ['sigla'], unique=True)
    op.create_table('sap_categoria_evento',
    sa.Column('id_categoria_evento', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('id_tipo_evento', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codigo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=5), nullable=False),
    sa.Column('cor_texto', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8), nullable=True),
    sa.Column('cor_fundo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8), nullable=True),
    sa.Column('url_icone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria_evento'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('codigo'), 'sap_categoria_evento', ['codigo'], unique=True)
    op.create_table('sap_unidade',
    sa.Column('id_unidade', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('nome_fantasia', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('nome_curto', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=True),
    sa.Column('tipo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('logradouro', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('id_bairro', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_equipamento_smct', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('telefone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15), nullable=True),
    sa.Column('gerencial', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('habilitado', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('removido', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('codigo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=5), nullable=True),
    sa.Column('data_instalacao', sa.DATE(), nullable=True),
    sa.Column('dias_folga', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15), nullable=True),
    sa.Column('url_imagem', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('latitude', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('longitude', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.ForeignKeyConstraint(['id_bairro'], ['sap_bairro.id_bairro'], name=op.f('fk_unidade_bairro'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_equipamento_smct'], ['equipamento_smct.id_equipamento_smct'], name=op.f('fk_unidade_smct'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_unidade'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('codigo'), 'sap_unidade', ['codigo'], unique=True)
    op.create_table('sap_programacao',
    sa.Column('id_programacao', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_evento', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_unidade', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_espaco', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_funcionario', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_inicio', sa.DATE(), nullable=False),
    sa.Column('data_termino', sa.DATE(), nullable=False),
    sa.Column('inicio_inscricao', sa.DATE(), nullable=False),
    sa.Column('termino_inscricao', sa.DATE(), nullable=False),
    sa.Column('numero_vagas', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vagas_excedentes', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('codigo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('quorum', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('habilitado', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('inscricao_publica', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('congelado_em', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id_espaco'], ['sap_espaco.id_espaco'], name=op.f('fk_programacao_espaco'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_evento'], ['sap_evento.id_evento'], name=op.f('fk_programacao_evento'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_unidade'], ['sap_unidade.id_unidade'], name=op.f('fk_programacao_unidade'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_programacao'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('codigo'), 'sap_programacao', ['codigo'], unique=True)
    op.create_table('sap_grupo',
    sa.Column('id_grupo', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('descricao', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('removido_em', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id_grupo'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('nome'), 'sap_grupo', ['nome'], unique=True)
    op.create_table('sap_deficiencia',
    sa.Column('id_deficiencia', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome_deficiencia', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('removido', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_deficiencia'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('unidade_recurso',
    sa.Column('id_unidade_recurso', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_unidade', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_espaco', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('descricao', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('criado_em', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('atualizado_em', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_espaco'], ['sap_espaco.id_espaco'], name=op.f('fk_recurso_espaco'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_unidade'], ['sap_unidade.id_unidade'], name=op.f('fk_recurso_unidade'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_unidade_recurso'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sap_pessoa',
    sa.Column('id_pessoa', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_deficiencia', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_escolaridade', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_instituicao_ensino', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('nome_social', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('nome_mae', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('sexo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1), nullable=False),
    sa.Column('etnia', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('nascimento', sa.DATE(), nullable=False),
    sa.Column('logradouro', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('id_bairro', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cep', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('id_pais', mysql.INTEGER(), server_default=sa.text("'33'"), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=True),
    sa.Column('email_ativado_em', mysql.DATETIME(), nullable=True),
    sa.Column('telefone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15), nullable=True),
    sa.Column('celular', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15), nullable=True),
    sa.Column('cpf', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=11), nullable=True),
    sa.Column('rg_numero', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15), nullable=True),
    sa.Column('rg_emissor', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15), nullable=True),
    sa.Column('motivo_cadastro', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('passaporte', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('interesses', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('ocupacao', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('observacao', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('foto', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40), nullable=True),
    sa.Column('avatar', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40), nullable=True),
    sa.Column('idioma', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2), server_default=sa.text("'pt'"), nullable=True),
    sa.Column('data_ultima_modificacao', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('pendente', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('importado', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('removido', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('direitos_imagem', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('atendido_smpd', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('servidor_sme', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('servidor_sme_matricula', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('servidor_sme_lotacao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('servidor_sme_cargo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('em_situacao_rua', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('validado_por', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('validado_em', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id_bairro'], ['sap_bairro.id_bairro'], name=op.f('fk_pessoa_bairro'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_deficiencia'], ['sap_deficiencia.id_deficiencia'], name=op.f('fk_pessoa_deficiencia'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_escolaridade'], ['sap_escolaridade.id_escolaridade'], name=op.f('fk_pessoa_escolaridade'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_instituicao_ensino'], ['sap_instituicao_ensino.id_instituicao_ensino'], name=op.f('fk_pessoa_instituicao'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_pessoa'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('cpf'), 'sap_pessoa', ['cpf'], unique=True)
    op.create_table('equipamento_smct',
    sa.Column('id_equipamento_smct', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('descricao', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('criado_em', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('atualizado_em', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id_equipamento_smct'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('nome'), 'equipamento_smct', ['nome'], unique=True)
    op.create_table('sap_equipamento',
    sa.Column('id_equipamento', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_espaco', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('descricao', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('identificacao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('endereco_mac', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('compartilhado', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('galeria', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('habilitado', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('removido', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_espaco'], ['sap_espaco.id_espaco'], name=op.f('fk_equipamento_espaco'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_equipamento'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('unidade_recurso_item',
    sa.Column('id_unidade_recurso_item', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_unidade_recurso', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome_item', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('quantidade', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('descricao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('criado_em', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('atualizado_em', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_unidade_recurso'], ['unidade_recurso.id_unidade_recurso'], name=op.f('fk_item_recurso'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_unidade_recurso_item'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sap_bairro',
    sa.Column('id_bairro', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_cidade', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('codigo_zepp', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_cidade'], ['sap_cidade.id_cidade'], name=op.f('fk_bairro_cidade'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_bairro'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sap_usuario',
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_pessoa', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_grupo', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('login', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('senha', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('ultimo_acesso', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id_grupo'], ['sap_grupo.id_grupo'], name=op.f('fk_usuario_grupo'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_pessoa'], ['sap_pessoa.id_pessoa'], name=op.f('fk_usuario_pessoa'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('login'), 'sap_usuario', ['login'], unique=True)
    op.create_index(op.f('id_pessoa'), 'sap_usuario', ['id_pessoa'], unique=True)
    op.create_table('rag_chunk',
    sa.Column('chunk_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('document_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('chunk_order', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chunk_text', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('metadata_json', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['rag_document.document_id'], name=op.f('fk_chunk_document'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_rag_chunk_doc'), 'rag_chunk', ['document_id'], unique=False)
    op.create_table('sap_certificado',
    sa.Column('id_certificado', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_inscricao_evento', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_certificado_modelo', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('conteudo_html', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('variaveis', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('codigo_autenticidade', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=24), nullable=True),
    sa.Column('inserido_em', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('atualizado_em', mysql.DATETIME(), nullable=True),
    sa.Column('removido_em', mysql.DATETIME(), nullable=True),
    sa.Column('revogado_em', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id_certificado_modelo'], ['sap_certificado_modelo.id_certificado_modelo'], name=op.f('fk_certificado_modelo'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_inscricao_evento'], ['sap_inscricao_evento.id_inscricao_evento'], name=op.f('fk_certificado_inscricao'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_certificado'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('codigo_autenticidade'), 'sap_certificado', ['codigo_autenticidade'], unique=True)
    op.create_table('agente_conhecimento',
    sa.Column('id_agente_conhecimento', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_agente_fonte_dados', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('titulo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('descricao', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('tipo_documento', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), server_default=sa.text("'ativo'"), nullable=False),
    sa.Column('criado_em', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('atualizado_em', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_agente_fonte_dados'], ['agente_fonte_dados.id_agente_fonte_dados'], name=op.f('fk_conhecimento_fonte'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_agente_conhecimento'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rag_document',
    sa.Column('document_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('source', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('source_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('document_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('body', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('metadata_json', mysql.JSON(), nullable=True),
    sa.Column('content_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('document_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_rag_doc_type'), 'rag_document', ['document_type'], unique=False)
    # ### end Alembic commands ###
