"""id de conversa

Revision ID: 694f1de170b4
Revises: 5aee76d1c61f
Create Date: 2026-06-23 18:01:52.087256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '694f1de170b4'
down_revision: Union[str, None] = '5aee76d1c61f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consents')
    op.add_column('messages', sa.Column('id_conversa', sa.String(length=100), nullable=True))
    op.add_column('usuarios', sa.Column('status', sa.String(length=50), nullable=True))
    op.drop_column('usuarios', 'ativo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('ativo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('usuarios', 'status')
    op.drop_column('messages', 'id_conversa')
    op.create_table('consents',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('permissao', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('ativo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('criado_em', mysql.DATETIME(), nullable=True),
    sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name=op.f('consents_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
