"""update 12/06

Revision ID: c14abc417c5f
Revises: f0bfe7e615d4
Create Date: 2026-06-12 23:11:12.309813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c14abc417c5f'
down_revision: Union[str, None] = 'f0bfe7e615d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('conversa', sa.JSON(), nullable=False))
    op.drop_column('messages', 'role')
    op.drop_column('messages', 'conteudo')
    op.add_column('usuarios', sa.Column('nascimento', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'nascimento')
    op.add_column('messages', sa.Column('conteudo', mysql.TEXT(), nullable=False))
    op.add_column('messages', sa.Column('role', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('messages', 'conversa')
    # ### end Alembic commands ###
