"""update

Revision ID: f0bfe7e615d4
Revises: 5c41fa5b2cc9
Create Date: 2026-06-10 12:31:28.114703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f0bfe7e615d4'
down_revision: Union[str, None] = '5c41fa5b2cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consents', sa.Column('id_usuario', sa.Integer(), nullable=False))
    op.drop_constraint('consents_ibfk_1', 'consents', type_='foreignkey')
    op.create_foreign_key(None, 'consents', 'usuarios', ['id_usuario'], ['id'])
    op.drop_column('consents', 'usuario_id')
    op.add_column('messages', sa.Column('id_usuario', sa.Integer(), nullable=False))
    op.drop_constraint('messages_ibfk_1', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'usuarios', ['id_usuario'], ['id'])
    op.drop_column('messages', 'usuario_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_ibfk_1', 'messages', 'usuarios', ['usuario_id'], ['id'])
    op.drop_column('messages', 'id_usuario')
    op.add_column('consents', sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'consents', type_='foreignkey')
    op.create_foreign_key('consents_ibfk_1', 'consents', 'usuarios', ['usuario_id'], ['id'])
    op.drop_column('consents', 'id_usuario')
    # ### end Alembic commands ###
